export default function Event() {
  return (
    <section id="event" className="w-full px-5 xl:px-0 py-10 flex flex-col">
        <p className="font-agencyGothicCTBold text-7xl sm:text-9xl text-[#004968] text-center">bar citizen</p>
        <p className="font-agencyGothicCTBold text-7xl sm:text-9xl text-[#004968] text-center">valencia 2024</p>
        <p className="text-2xl font-semibold my-10">El día 6 de Abril os esperamos a toda la comunidad de Star Citizen en el evento Bar Citizen Valencia 2024<br/>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque et ante quis leo viverra luctus. Integer volutpat purus ut ultricies pellentesque. Sed ut tortor at lectus efficitur elementum a et lectus. Fusce nibh metus, volutpat sit amet nisi et, efficitur ullamcorper ligula. Vivamus non ultricies diam, eu hendrerit urna. Integer quis lorem nec velit pulvinar maximus vitae id libero. Aliquam erat volutpat. Sed ac viverra sem. Integer consectetur varius libero, in lobortis dui condimentum sit amet. Maecenas non arcu eu diam ornare volutpat. Suspendisse porta nisi a commodo sagittis. Nunc quis metus eget purus hendrerit dapibus lobortis vitae sapien. Proin nec porttitor velit. Suspendisse id tellus libero. Nam hendrerit ullamcorper nibh, gravida porttitor lectus faucibus eu. Duis ultrices molestie leo, id placerat felis ornare sit amet.<br/>Vivamus ac libero at eros bibendum pellentesque. Vestibulum elementum consectetur sem, gravida tincidunt dolor facilisis quis. Integer at purus in sapien scelerisque suscipit. Integer ac nunc sed sapien viverra luctus ac nec nunc. Mauris venenatis volutpat rutrum. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nunc lectus arcu, fringilla ut convallis vitae, gravida at sem.</p>
        <iframe className="aspect-video w-full h-auto" width="560" height="315" src="https://www.youtube.com/embed/rGrvUyF98yE?si=mA1rgB6z7qVJZZvI" title="YouTube video player" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen></iframe>
    </section>
  );
}
